Feature: Output apache configuration file

  In order to run my application as an apache virtualhost
  As a user of the library
  I want to output a apache virtualhost configuration.

  Scenario: using command-line options, multiple upstreams
    When I run `bundle exec vhost-generator -g apache -o assets_expire_in=15d -a testapp -f html -l 80,81 -s localhost,my.server -p 5000,5001,5002 -r /myapp`
    Then the output should match /FILE GENERATED BY.*EDIT AT YOUR OWN RISK/
    And the output should contain:
      """
      <VirtualHost *:80 *:81>
      """
    And the output should contain:
      """
        ServerName localhost
        ServerAlias my.server
      """
    And the output should match /DocumentRoot.*html/
    And the output should contain:
      """
        AllowEncodedSlashes On
      """
    And the output should contain:
      """
        <Proxy balancer://testapp>
          BalancerMember http://localhost:5000
          BalancerMember http://localhost:5001
          BalancerMember http://localhost:5002
        </Proxy>
      """
    And the output should contain:
      """
        # Redirect all non-static requests to instances
        RewriteEngine On
        RewriteCond %{DOCUMENT_ROOT}/%{REQUEST_FILENAME} !-f
        RewriteRule ^/(.*)$ balancer://testapp%{REQUEST_URI} [P,QSA,L]
      """
    And the output should contain:
      """
        <Location /myapp/assets>
          ExpiresActive On
          Header unset ETag
          FileETag None
          ExpiresDefault "access plus 15 days"
        </Location>
      """
    And the output should contain:
      """
        ErrorDocument 500 /500.html
        ErrorDocument 502 /500.html
        ErrorDocument 503 /500.html
        ErrorDocument 504 /500.html
        LimitRequestBody 2147483647
        KeepAliveTimeout 10
      </VirtualHost>
      """

  Scenario: using environment variables, multiple upstreams
    When I set env variable "GENERATOR" to "apache"
    And I set env variable "GENERATOR_OPTIONS" to "assets_expire_in=15d"
    And I set env variable "APPLICATION" to "testapp"
    And I set env variable "STATIC_FOLDER" to "html"
    And I set env variable "SERVER_PORTS" to "80,81"
    And I set env variable "SERVER_NAMES" to "localhost,my.server"
    And I set env variable "INSTANCE_PORTS" to "5000,5001,5002"
    And I set env variable "RAILS_RELATIVE_URL_ROOT" to "/myapp"
    And I run `bundle exec vhost-generator`
    Then the output should match /FILE GENERATED BY.*EDIT AT YOUR OWN RISK/
    And the output should contain:
      """
      <VirtualHost *:80 *:81>
      """
    And the output should contain:
      """
        ServerName localhost
        ServerAlias my.server
      """
    And the output should match /DocumentRoot.*html/
    And the output should contain:
      """
        AllowEncodedSlashes On
      """
    And the output should contain:
      """
        <Proxy balancer://testapp>
          BalancerMember http://localhost:5000
          BalancerMember http://localhost:5001
          BalancerMember http://localhost:5002
        </Proxy>
      """
    And the output should contain:
      """
        # Redirect all non-static requests to instances
        RewriteEngine On
        RewriteCond %{DOCUMENT_ROOT}/%{REQUEST_FILENAME} !-f
        RewriteRule ^/(.*)$ balancer://testapp%{REQUEST_URI} [P,QSA,L]
      """
    And the output should contain:
      """
        <Location /myapp/assets>
          ExpiresActive On
          Header unset ETag
          FileETag None
          ExpiresDefault "access plus 15 days"
        </Location>
      """
    And the output should contain:
      """
        ErrorDocument 500 /500.html
        ErrorDocument 502 /500.html
        ErrorDocument 503 /500.html
        ErrorDocument 504 /500.html
        LimitRequestBody 2147483647
        KeepAliveTimeout 10
      </VirtualHost>
      """

  Scenario: using command-line options, single upstream
    When I run `bundle exec vhost-generator -g apache -o assets_expire_in=15d -a testapp -f html -l 80,81 -s localhost,my.server -p 5000 -r /myapp`
    Then the output should match /FILE GENERATED BY.*EDIT AT YOUR OWN RISK/
    And the output should contain:
      """
      <VirtualHost *:80 *:81>
      """
    And the output should contain:
      """
        ServerName localhost
        ServerAlias my.server
      """
    And the output should match /DocumentRoot.*html/
    And the output should contain:
      """
        AllowEncodedSlashes On
      """
    And the output should contain:
      """
        # Redirect all non-static requests to instances
        RewriteEngine On
        RewriteCond %{DOCUMENT_ROOT}/%{REQUEST_FILENAME} !-f
        RewriteRule ^/(.*)$ http://localhost:5000%{REQUEST_URI} [P,QSA,L]
      """
    And the output should contain:
      """
        <Location /myapp/assets>
          ExpiresActive On
          Header unset ETag
          FileETag None
          ExpiresDefault "access plus 15 days"
        </Location>
      """
    And the output should contain:
      """
        ErrorDocument 500 /500.html
        ErrorDocument 502 /500.html
        ErrorDocument 503 /500.html
        ErrorDocument 504 /500.html
        LimitRequestBody 2147483647
        KeepAliveTimeout 10
      </VirtualHost>
      """

  Scenario: using environment variables, single upstream
    When I set env variable "GENERATOR" to "apache"
    And I set env variable "GENERATOR_OPTIONS" to "assets_expire_in=15d"
    And I set env variable "APPLICATION" to "testapp"
    And I set env variable "STATIC_FOLDER" to "html"
    And I set env variable "SERVER_PORTS" to "80,81"
    And I set env variable "SERVER_NAMES" to "localhost,my.server"
    And I set env variable "INSTANCE_PORTS" to "5000"
    And I set env variable "RAILS_RELATIVE_URL_ROOT" to "/myapp"
    And I run `bundle exec vhost-generator`
    Then the output should match /FILE GENERATED BY.*EDIT AT YOUR OWN RISK/
    And the output should contain:
      """
      <VirtualHost *:80 *:81>
      """
    And the output should contain:
      """
        ServerName localhost
        ServerAlias my.server
      """
    And the output should match /DocumentRoot.*html/
    And the output should contain:
      """
        AllowEncodedSlashes On
      """
    And the output should contain:
      """
        # Redirect all non-static requests to instances
        RewriteEngine On
        RewriteCond %{DOCUMENT_ROOT}/%{REQUEST_FILENAME} !-f
        RewriteRule ^/(.*)$ http://localhost:5000%{REQUEST_URI} [P,QSA,L]
      """
    And the output should contain:
      """
        <Location /myapp/assets>
          ExpiresActive On
          Header unset ETag
          FileETag None
          ExpiresDefault "access plus 15 days"
        </Location>
      """
    And the output should contain:
      """
        ErrorDocument 500 /500.html
        ErrorDocument 502 /500.html
        ErrorDocument 503 /500.html
        ErrorDocument 504 /500.html
        LimitRequestBody 2147483647
        KeepAliveTimeout 10
      </VirtualHost>
      """
